package br.com.fabricads.demo;

import org.apache.commons.math3.util.Precision;

rule "CalcularDescontos"
    dialect "mvel"
    no-loop true
    when
        $funcionario : Funcionario( $verbas : verbas != null)
        not Verba( valor == null , tipo == Tipo.DESCONTO ) from $verbas
        not Verba( codigo == 97 ) from $verbas
        $descontos : Double() from accumulate ( Verba( $valor : valor != null, tipo == Tipo.DESCONTO) from $verbas , sum ( $valor ) )
    then
        Verba totalDescontos = new Verba();
        totalDescontos.setCodigo(97);
        totalDescontos.setDescricao("Total de Descontos");
        totalDescontos.setValor(Precision.round($descontos, 2));
        $funcionario.getVerbas().add(totalDescontos);
        update($funcionario);
end