package br.com.fabricads.demo;

import org.apache.commons.math3.util.Precision;

rule "CalcularSalarioLiquido"
    dialect "mvel"
    no-loop true
    when
        $funcionario : Funcionario( $verbas : verbas != null )
        $verbaProventos : Verba( codigo == 96 ) from $verbas
        $verbaDescontos : Verba( codigo == 97 ) from $verbas
        not Verba( codigo == 98 ) from $verbas
    then
        $funcionario.getVerbas().add(Verba.builder().codigo(98).descricao("Salario Liquido").valor(Precision.round($verbaProventos.getValor() - $verbaDescontos.getValor(), 2)).build());
        update($funcionario);
end
