package br.com.fabricads.demo;

import org.apache.commons.math3.util.Precision;

/* Após todos os descontos tiverem valores preenchidos faz uma somatoria */
rule "CalcularDescontos"
    dialect "mvel"
    no-loop true
    when
        $funcionario : Funcionario( $verbas : verbas != null)
        not Verba( valor == null , tipo == Tipo.DESCONTO ) from $verbas
        not Verba( codigo == 97 ) from $verbas
        $descontos : Double() from accumulate ( Verba( $valor : valor != null, tipo == Tipo.DESCONTO) from $verbas , sum ( $valor ) )
    then
        $funcionario.getVerbas().add(Verba.builder().codigo(97).descricao("Total de Descontos").valor(Precision.round($descontos, 2)).build());
        update($funcionario);
end