package br.com.fabricads.demo;

import org.apache.commons.math3.util.Precision;

rule "CalcularProventos"
    dialect "mvel"
    no-loop true
    when
        $funcionario : Funcionario( $verbas : verbas != null )
        not Verba( valor == null , tipo == Tipo.PROVENTO ) from $verbas
        not Verba( codigo == 96 ) from $verbas
        $proventos : Double() from accumulate ( Verba( $valor : valor != null, tipo == Tipo.PROVENTO ) from $verbas , sum ( $valor ) )
    then
        $funcionario.getVerbas().add(Verba.builder().codigo(96).descricao("Total de Proventos").valor(Precision.round($proventos, 2)).build());
        update($funcionario);
end